[34m[1mwandb[0m: [33mWARNING[0m Found log directory outside of given root_logdir, dropping given root_logdir for event file in /home/alexhuge/Documents/GitHub/grmini_gait/humanoidgym/logs/grmini/Feb09_09-46-59_
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    train(args)
  File "train.py", line 39, in train
    ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
  File "/home/alexhuge/Documents/GitHub/grmini_gait/humanoidgym/humanoid/algo/ppo/on_policy_runner.py", line 130, in learn
    obs, privileged_obs, rewards, dones, infos = self.env.step(actions)
  File "/home/alexhuge/Documents/GitHub/grmini_gait/humanoidgym/humanoid/envs/custom/grmini_env.py", line 200, in step
    return super().step(actions)
  File "/home/alexhuge/Documents/GitHub/grmini_gait/humanoidgym/humanoid/envs/base/legged_robot.py", line 93, in step
    self.render()
  File "/home/alexhuge/Documents/GitHub/grmini_gait/humanoidgym/humanoid/envs/base/base_task.py", line 170, in render
    self.gym.draw_viewer(self.viewer, self.sim, True)
KeyboardInterrupt
